spring:
      datasource:
        url: jdbc:postgresql://localhost:5433/payment
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

      kafka:
        bootstrap-servers: localhost:9092 
        producer:
            bootstrap-servers: localhost:9092 
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: paymentConfirmation:com.erincak.ecommerce.notification.PaymentNotificationRequest
server:
  port: 8060