spring:
    datasource: 
        url: jdbc:postgresql://localhost:5433/product
        username: user
        password: password
        driver-class-name: org.postgresql.Driver

    jpa: 
        hibernate: 
            ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-description: "init"
        baseline-version: 0
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}

server:
    port: 8050